In [44]:
# 1st install sklearn 
# import all the libraries neeeded 

import numpy as np
import pandas as pd
from sklearn import neighbors, metrics
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [184]:
## Import the dataset to be used in this work 
# https://archive.ics.uci.edu/ml/datasets.php : many dataset availables here
# we download the car evaluation dataset for our project
# import os
# os.getcwd() : to get the working directory and save your downloaded data there
data = pd.read_csv('car.data')
print(data.head())

  buying  maint  doors  persons lug_boot  safety  class
0  vhigh  vhigh      2        2    small     low  unacc
1  vhigh  vhigh      2        2    small     med  unacc
2  vhigh  vhigh      2        2    small    high  unacc
3  vhigh  vhigh      2        2      med     low  unacc
4  vhigh  vhigh      2        2      med     med  unacc


In [188]:
# from the uploaded data, let's create labels and features
# from the variables of the data, the most significants ones that can bestly identify the class are 'buying', 'maintainance' and 'safety'
# they will constitute our selected features for classification
X = data.iloc[:, np.array([0,1,5])].values
y = data.iloc[:,6]


In [191]:
# we have strings : high, low etc and we can't put it directly in to a ML algorithm. Let's convert it into numbers using the
# sklearn function LabelEncoder

# Encording the features
Le = LabelEncoder()
for i in range(len(X[0])):
    X[:,i] = Le.fit_transform(X[:,i])

print(X)


[[3 3 1]
 [3 3 2]
 [3 3 0]
 ...
 [1 1 1]
 [1 1 2]
 [1 1 0]]


In [192]:
# Encording the labels
# y = Le.fit_transform(y)

# we can also encord the labels by creating dictionary as :
label_mapping = {'unacc':0, 'acc':1, 'good':2, 'vgood':3} # dictionary 
y = y.map(label_mapping)
y = np.array(y)
type(y)

numpy.ndarray

In [202]:
# splitting the data into the training and testing set

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0, train_size = .8)

In [203]:
## model creation : KNN
knn = neighbors.KNeighborsClassifier(n_neighbors=25, weights='uniform')

knn.fit(X_train, y_train) # training the model with the training data

# prediction

prediction = knn.predict(X_test)

# accuray 
accuracy  = metrics.accuracy_score(y_test, prediction)

print("prediction", prediction)
print("accuracy", accuracy)

prediction [0 0 0 0 0 0 0 1 1 0 0 0 2 0 0 0 0 0 0 0 3 1 2 0 0 0 0 1 0 0 3 1 0 1 2 0 0
 0 0 0 0 1 0 0 3 0 0 0 0 0 0 0 0 0 1 0 2 0 0 0 1 0 0 0 0 1 1 0 0 2 0 1 1 1
 0 1 0 1 1 0 0 0 0 1 0 0 0 1 0 0 1 1 0 0 0 0 0 0 1 0 1 0 0 0 2 0 0 1 0 0 3
 0 0 1 0 0 1 0 0 3 0 0 3 0 1 0 0 1 2 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0
 1 0 1 0 0 0 0 1 0 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 3 1 0 1 1 1 0 1
 0 3 0 0 0 0 1 0 0 0 1 3 1 1 0 0 0 1 0 0 0 0 0 0 3 3 1 0 0 0 1 0 1 0 0 0 1
 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 2 0 1 0 0 0 0 1 0 1 0 3 0 0 0
 0 0 0 0 1 0 0 3 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 0 3 1 0 1 0 0 0 3 0
 0 1 1 1 1 1 1 2 0 0 1 0 1 0 0 1 1 0 0 0 0 1 0 1 0 0 0 1 1 0 0 1 0 0 1 0 0
 0 0 0 0 0 0 0 0 3 0 1 0 0]
accuracy 0.7658959537572254


In [205]:
a = 56
print("actual value:", y[a])
print("predicted value", knn.predict(X)[a])

actual value: 0
predicted value 0
